//! Top-level encoder driver.
//!
//! Reference: `avm/av2/encoder/{encoder.c,encode_strategy.c}`.

use core::fmt;

use crate::common::image::Frame;

use crate::bitstream::{
    BitstreamError, FrameHeaderConfig, ObuHeader, ObuType, SequenceHeaderConfig, write_annexb_obu,
    write_frame_header_payload, write_sequence_header_payload,
};
use crate::encodetxb::encode_txb;
use crate::frame::build_frame_plan;
use crate::intra::pick_intra_mode;
use crate::partition::pick_partition;
use crate::quantize::quantize_zero;
use crate::tokenize::tokenize;
use crate::transform::pick_transform;

/// Encoder configuration. Expanded as stages come online.
#[derive(Clone, Copy, Debug)]
pub struct Config {
    /// Frame width in luma samples (rounded to even for 4:2:0).
    pub width: u32,
    /// Frame height in luma samples (rounded to even for 4:2:0).
    pub height: u32,
    /// Bit depth: 8 or 10.
    pub bit_depth: u8,
    /// Base quantization index (`base_q_idx`), 0..=255.
    pub base_qindex: u8,
}

impl Config {
    /// A minimal still-image keyframe configuration.
    pub fn new(width: u32, height: u32, bit_depth: u8, base_qindex: u8) -> Self {
        Self {
            width,
            height,
            bit_depth,
            base_qindex,
        }
    }

    /// Validate the currently supported skeleton profile.
    pub fn validate(self) -> Result<(), EncodeError> {
        if self.width != 128 || self.height != 128 {
            return Err(EncodeError::UnsupportedGeometry {
                width: self.width,
                height: self.height,
            });
        }
        if self.bit_depth != 8 {
            return Err(EncodeError::UnsupportedBitDepth(self.bit_depth));
        }
        Ok(())
    }
}

/// The AV2 encoder. The pipeline is wired here and filled in stage by stage.
pub struct Encoder {
    cfg: Config,
}

impl Encoder {
    /// Create a new encoder for the given configuration.
    pub fn new(cfg: Config) -> Result<Self, EncodeError> {
        cfg.validate()?;
        Ok(Self { cfg })
    }

    /// The configuration this encoder was created with.
    pub fn config(&self) -> Config {
        self.cfg
    }

    /// Encode a single 128x128 8-bit 4:2:0 still frame to a raw `.obu` byte stream.
    pub fn encode_frame(&self, frame: &Frame) -> Result<Vec<u8>, EncodeError> {
        self.validate_frame(frame)?;

        let partition = pick_partition();
        let intra = pick_intra_mode();
        let transform = pick_transform();
        let qblock = quantize_zero(self.cfg.base_qindex);
        let tokens = tokenize(qblock);
        let txb = encode_txb(tokens);
        let _plan = build_frame_plan(partition, intra, transform, txb);

        // The deterministic 128x128 8-bit 4:2:0 still-picture, one-superblock, DC/skip
        // bootstrap. OBU framing, the sequence header, and the uncompressed frame-header
        // preamble are now generated by real Rust writers; the remaining frame-header tool
        // flags and the range-coded tile data are still emitted as their validated bootstrap
        // constant tails (see bitstream.rs) until each gains a Rust writer.
        let mut out = Vec::new();
        write_annexb_obu(
            &mut out,
            ObuHeader::new(ObuType::TemporalDelimiter),
            MINIMAL_TEMPORAL_DELIMITER_PAYLOAD,
        )?;
        let sequence_header = write_sequence_header_payload(SequenceHeaderConfig::new(
            self.cfg.width,
            self.cfg.height,
            self.cfg.bit_depth,
        ))?;
        write_annexb_obu(
            &mut out,
            ObuHeader::new(ObuType::SequenceHeader),
            &sequence_header,
        )?;
        let frame_header = write_frame_header_payload(FrameHeaderConfig::new(
            self.cfg.width,
            self.cfg.height,
            self.cfg.bit_depth,
        ))?;
        write_annexb_obu(
            &mut out,
            ObuHeader::new(ObuType::ClosedLoopKey),
            &frame_header,
        )?;
        Ok(out)
    }

    fn validate_frame(&self, frame: &Frame) -> Result<(), EncodeError> {
        if frame.width() != self.cfg.width as usize || frame.height() != self.cfg.height as usize {
            return Err(EncodeError::FrameGeometryMismatch {
                config_width: self.cfg.width,
                config_height: self.cfg.height,
                frame_width: frame.width(),
                frame_height: frame.height(),
            });
        }
        if frame.bit_depth != self.cfg.bit_depth {
            return Err(EncodeError::FrameBitDepthMismatch {
                config: self.cfg.bit_depth,
                frame: frame.bit_depth,
            });
        }
        if frame.subsampling_x != 1 || frame.subsampling_y != 1 {
            return Err(EncodeError::UnsupportedChromaSubsampling {
                x: frame.subsampling_x,
                y: frame.subsampling_y,
            });
        }
        Ok(())
    }
}

/// Encoder failure.
#[derive(Debug)]
pub enum EncodeError {
    /// Only the first skeleton geometry is implemented.
    UnsupportedGeometry { width: u32, height: u32 },
    /// Only 8-bit output is implemented.
    UnsupportedBitDepth(u8),
    /// Only 4:2:0 is implemented.
    UnsupportedChromaSubsampling { x: u8, y: u8 },
    /// Input frame dimensions do not match the encoder configuration.
    FrameGeometryMismatch {
        config_width: u32,
        config_height: u32,
        frame_width: usize,
        frame_height: usize,
    },
    /// Input frame bit depth does not match the encoder configuration.
    FrameBitDepthMismatch { config: u8, frame: u8 },
    /// Low-level bitstream construction failed.
    Bitstream(BitstreamError),
}

impl fmt::Display for EncodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnsupportedGeometry { width, height } => {
                write!(
                    f,
                    "unsupported geometry {width}x{height}; skeleton supports 128x128 only"
                )
            }
            Self::UnsupportedBitDepth(bit_depth) => {
                write!(
                    f,
                    "unsupported bit depth {bit_depth}; skeleton supports 8-bit only"
                )
            }
            Self::UnsupportedChromaSubsampling { x, y } => {
                write!(
                    f,
                    "unsupported chroma subsampling {x}:{y}; skeleton supports 4:2:0 only"
                )
            }
            Self::FrameGeometryMismatch {
                config_width,
                config_height,
                frame_width,
                frame_height,
            } => write!(
                f,
                "frame geometry {frame_width}x{frame_height} does not match encoder config {config_width}x{config_height}"
            ),
            Self::FrameBitDepthMismatch { config, frame } => {
                write!(
                    f,
                    "frame bit depth {frame} does not match encoder config {config}"
                )
            }
            Self::Bitstream(err) => err.fmt(f),
        }
    }
}

impl std::error::Error for EncodeError {}

impl From<BitstreamError> for EncodeError {
    fn from(value: BitstreamError) -> Self {
        Self::Bitstream(value)
    }
}

const MINIMAL_TEMPORAL_DELIMITER_PAYLOAD: &[u8] = &[];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_rejects_unsupported_skeleton_values() {
        assert!(matches!(
            Config::new(64, 128, 8, 128).validate(),
            Err(EncodeError::UnsupportedGeometry { .. })
        ));
        assert!(matches!(
            Config::new(128, 128, 10, 128).validate(),
            Err(EncodeError::UnsupportedBitDepth(10))
        ));
    }

    #[test]
    fn encode_is_deterministic_for_supported_frame() {
        let frame = Frame::new_420(128, 128, 8);
        let enc = Encoder::new(Config::new(128, 128, 8, 128)).unwrap();
        let obu = enc.encode_frame(&frame).unwrap();
        assert_eq!(obu, enc.encode_frame(&frame).unwrap());
        assert_eq!(obu.len(), 25);
        assert_eq!(&obu[..2], &[1, 0x08]);
    }
}
