import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'overview',
    'open-source',
    {
      type: 'category',
      label: 'Get Started',
      collapsible: false,
      collapsed: false,
      items: ['installation', 'first-run', 'quick-start', 'docker'],
    },
    {
      type: 'category',
      label: 'Use Cases',
      collapsible: false,
      collapsed: false,
      items: ['jellyfin', 'av1'],
    },
    {
      type: 'category',
      label: 'Comparisons',
      collapsible: false,
      collapsed: false,
      items: [
        'alternatives/index',
        'alternatives/tdarr',
        'alternatives/fileflows',
        'migrate-from-tdarr',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: false,
      collapsed: false,
      items: [
        'hardware',
        'gpu-passthrough',
        'library-setup',
        'profiles',
        'stream-rules',
        'scheduling',
        'notifications',
        'library-doctor',
        'web-interface',
      ],
    },
    {
      type: 'category',
      label: 'Hardware',
      collapsible: false,
      collapsed: false,
      items: [
        'hardware/nvidia',
        'hardware/intel',
        'hardware/amd',
        'hardware/apple',
        'hardware/cpu',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      collapsed: false,
      items: [
        'configuration-reference',
        'api',
        'codecs',
        'skip-decisions',
        'engine-modes',
        'environment-variables',
        'database-schema',
        'architecture',
        'troubleshooting',
        'troubleshooting/nvenc-not-detected',
        'troubleshooting/vaapi-not-detected',
        'troubleshooting/jellyfin-direct-play-failing',
        'faq',
        'changelog',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsible: false,
      collapsed: false,
      items: ['contributing/overview', 'contributing/development'],
    },
  ],
};

export default sidebars;
